export const TOGGLEFADEIN = 'TOGGLEFADEIN';
export const REINITIALIZE = 'REINITIALIZE';
export const INCREMENTINDEX = 'INCREMENTINDEX';

export const MODALOPEN = 'MODALOPEN';
export const MODALCLOSE = 'MODALCLOSE'

export const UPDATE_QUOTE_OFFSET = 'UPDATE_QUOTE_OFFSET';
export const UPDATE_SKILLS_DOM_ELEMENT = 'UPDATE_SKILLS_DOM_ELEMENT';
export const UPDATE_QUOTE_DOM_ELEMENT = 'UPDATE_QUOTE_DOM_ELEMENT';
export const UPDATE_CURRENT_ROLE_DOM_ELEMENT= 'UPDATE_CURRENT_ROLE_DOM_ELEMENT';